language: java
jdk:
  - oraclejdk8
  
addons:
  artifacts: true
  s3_region: "us-west-1" # defaults to "us-east-1"
  
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ThunderGemios10"
  - git config --local user.email "thundergemios10@gmail.com"
